# Generated by Django 5.2.7 on 2026-08-17 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date/time this resource was created.')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created.')),
                ('collector', models.CharField(help_text='Collector name (collector_type / API path segment)', max_length=100)),
                ('source', models.CharField(default='local', help_text='Origin of the data; defaults to the local install. Distinguishes multi-cluster origin.', max_length=255)),
                ('since', models.DateTimeField(blank=True, help_text='`since` passed to the collector (inclusive), if any', null=True)),
                ('until', models.DateTimeField(blank=True, help_text='`until` passed to the collector (exclusive), if any', null=True)),
                ('started_at', models.DateTimeField(help_text='When collection (gather) started')),
                ('finished_at', models.DateTimeField(help_text='When collection (gather) finished')),
                ('payload', models.JSONField(default=dict, help_text='Raw pre-prepare() gather() output, JSON-serialisable')),
                ('created_by', models.ForeignKey(default=None, editable=False, help_text='The user who created this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analytics Payload',
                'verbose_name_plural': 'Analytics Payloads',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['collector', 'since'], name='analytics_a_collect_2c3ed1_idx'), models.Index(fields=['collector', 'until'], name='analytics_a_collect_7842e4_idx'), models.Index(fields=['collector', 'started_at'], name='analytics_a_collect_712e4b_idx')],
                'unique_together': {('collector', 'source', 'since', 'until')},
            },
        ),
    ]
