# Generated by Django 5.2.7 on 2026-08-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticspayload',
            name='claimed_at',
            field=models.DateTimeField(blank=True, help_text='When an on-demand claim was staked (for stale-claim TTL)', null=True),
        ),
        migrations.AddField(
            model_name='analyticspayload',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Error message if collection failed'),
        ),
        migrations.AddField(
            model_name='analyticspayload',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='done', help_text='Collection state', max_length=10),
        ),
        migrations.AlterField(
            model_name='analyticspayload',
            name='finished_at',
            field=models.DateTimeField(blank=True, help_text='When collection (gather) finished', null=True),
        ),
        migrations.AlterField(
            model_name='analyticspayload',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When collection (gather) started', null=True),
        ),
    ]
